### ISSUE TITLE
Small doubt

### ISSUE THREAD

**Issue by KayDee** [DeborahK/Angular-GettingStarted#102]
https://github.com/DeborahK/Angular-GettingStarted/blob/99ccf5bde56b257c118a99de490f68e58c2cd65a/APM-Final/src/app/products/product.service.ts#L25

This is a line in the getProduct() for product detail view.
My questions: 
1. Why use pipe ? (lil unclear on it)
2. If map is used, why is its parameter of type ```IProducts[]```. Why the **[]** ?
3. Also, why not filter ?

**Comment by stefanolsenn** [comment]
In case you still are struggling:

1. See pipe as a kind of middleware. In the example we only want the product with that id. So we can kind of intercept the data, before it's returned to a component, or wherever the observable is subscribed from.  (You wouldn't get all the products and filter client-side in production) 

2. Because we expect an array of products. It's just good coding practice to strong type the data.

3. You could also use filter. find() returns the first element that matches the predicate. filter() returns all elements that matches the predicate.

**Comment by KayDee** [comment]
Got it. Mistook the map for the JS ```Array.map()```. Thanks.

**Comment by DeborahK** [comment]
I get so much span from github I didn't notice the question. Consider posting to the discussion tab for the course instead as I monitor those much more closely. :-)

1. The purpose of a pipe is to transform the that before displaying it. For example, say your database stores a value in weeks but you want to show the user the value in months. You could build a pipe that converted the number of weeks into months before displaying it.

2. The [] in the type: IProduct[] is typing the value as an *array* of objects with the IProduct interface. Just typing it as IProduct would mean that we expected it to be a single object with the IProduct interface.

3. As the prior poster stated, `find` returns the first match and `filter` returns all matches.

Hope this helps!

**Comment by KayDee** [comment]
> Consider posting to the discussion tab for the course instead as I monitor those much more closely. :-)

Thank you, i'll do that.
