### ISSUE TITLE
Question: How can implement pagination?

### ISSUE THREAD

**Issue by ksurendra** [DeborahK/Angular-GettingStarted#132]
Thanks for the example Deborah.

If we have a lot of records..

1. How can we implement pagination?
2. If we have pagination, will the filter work only the displayed products on the page or across all records?
3. Or should we wait until enters submit in the search box, then call the service -> fetch the records -> filter among them -> display on the page -> and pagination

Appreciate your help/advice.

**Comment by DeborahK** [comment]
If you have lots of records, you probably want to perform the filtering (and the pagination) on the server side, as part of the http request.

See this for an example: https://app.pluralsight.com/library/courses/angular-denver-2019-session-27

Hope this helps!

Since this isn't an issue with the provided code, I'm closing it.
