### ISSUE TITLE
I think the course is missing explanation on the #variable in templates

### ISSUE THREAD

**Issue by boynet** [DeborahK/Angular-GettingStarted#148]
I finished this course and followed to the next one, and suddenly there is #variables in the templates everywhere and I didnt know about it.

anyway really good course thanks a lot

**Comment by DeborahK** [comment]
Thank you for the feedback!

The #variable is called a `template reference variable`. It is used primarily for forms. You can see more about it here: https://angular.io/guide/template-reference-variables

Because of the scope of this course and the amount of information required to adequately cover forms, we decided to *not* include Angular forms in this course. Angular forms are instead covered in the "Angular Forms" course (which I assume is the one you are watching?) and the "Angular Reactive Forms" course. 

Since they are used in the "Angular Forms" course, consider also posting a suggestion for the "Angular Forms" course to provide more information on template reference variables.

Thanks again.
