### ISSUE TITLE
app.component.html is present but the app.component.ts has an inline template

### ISSUE THREAD

**Issue by egandro** [DeborahK/Angular-GettingStarted#54]
The file 'app.component.html' is somehow useless. The component has an inline template.

**Comment by DeborahK** [comment]
In the APM-Start folder, the default Angular CLI generated code uses that linked template. As we work through the course, we modify the `apm.component.ts` to use an inline template. So that file *was* used at the beginning of this course. I just did not add a step to remove it. I'm closing this issue.

Thanks!
