### ISSUE TITLE
products

### ISSUE THREAD

**Issue by lakshmi9999** [DeborahK/Angular-GettingStarted#58]
Hello, i am attaching my file here. There is  no error but it is not showing products in the browser after using the HTTP link. PLease respond quick, i am stuck here in the course

[product-list.component.zip](https://github.com/DeborahK/Angular-GettingStarted/files/1270442/product-list.component.zip)

**Comment by lakshmi9999** [comment]
please respond quick, i am stuck at this point and cannot go ahead in the course

**Comment by DeborahK** [comment]
I can't download your file and unzip it due to security constraints on my system. 

Are you seeing any errors in the console? Can you paste in the relevant code?

**Comment by DeborahK** [comment]
The fastest way to resolve your issue is to download the code using the Exercise Files tab for the course here: https://app.pluralsight.com/library/courses/angular-2-getting-started-update

Unzip it. Then find the folder for the module you are on. (There will be a folder for each module containing the code as of the end of that module.)

You can then use a folder compare utility to compare your code against mine to see where there may be a syntax error or missing statement.

Hope this helps.

**Comment by DeborahK** [comment]
I see you just closed this issue. Were you able to determine the source of your problem?

**Comment by lakshmi9999** [comment]
For importing throw, i made a mistake like add/operator/throw for add/observable/throw.

Thank you.

**Comment by DeborahK** [comment]
Glad you found the source of the problem!
