### ISSUE TITLE
how to use star component i always getting 5 starts and it was vertical

### ISSUE THREAD

**Issue by ashiqbca** [DeborahK/Angular-GettingStarted#62]
i am new to angular

**Comment by DeborahK** [comment]
I don't have much to go on here. The best thing to try is:
- Download the files from the Exercise tab for the course.
- Unzip it.
- Inside there is code "as of" the end of each module.
- Use a folder compare utility and compare your files to the files in the folder for the module you are on.

Let me know if that helps to resolve this issue.

**Comment by sureshp191** [comment]
Hello, when I tried to use the code as per your instructions, I see the below error, basically the content written within  template: ' '  should be in one line than multiple lines, please advise how to write in multiple lines so that its easy to maintain. Thanks


ERROR in ./src/app/app.component.ts
Module parse failed: C:\Training\Angular-GettingStarted-master\APM\node_modules\@ngtools\webpack\src\index.js!C:\Training\Angular-GettingStarted-master\APM\src\app\app.component.ts Unterminated string constant (31:18)
You may need an appropriate loader to handle this file type.
|     Component({
|         selector: 'pm-root',
|         template: '
|             < div > {}
|     }, { pageTitle: pageTitle }, /h1>
 @ ./src/app/app.module.ts 9:0-47
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

Below is the code: 
import { Component } from '@angular/core';

@Component({
  selector: 'pm-root',
  template: ' 
    <div> <h1>{{pageTitle}}</h1> 
          <div>My First Component </div> 
    </div> 
  '
})

export class AppComponent{
    pageTitle: string = 'Acme Product Management';
}

**Comment by DeborahK** [comment]
I'm going to close this issue. Please post future questions about the course or the sample application to the Discussion tab for the course here: https://app.pluralsight.com/library/courses/angular-2-getting-started-update/discussion
