### ISSUE TITLE
exporting services

### ISSUE THREAD

**Issue by sipuxd** [DeborahK/Angular-GettingStarted#64]
In section  #13 "Angular Modules", the video "Exports Array" says to  never export a service at 1:48 into the video?  I'm not sure what that means being we were show to use the export keyword when we created the product.service.ts file in section #9 of "Building a Service" at 42 seconds into the video...

Code example of export currently being used shown below:

@Injectable()
**export** class ProductService{ 

}

**Comment by DeborahK** [comment]
There is a difference between the "Exports Array" of an Angular module (as discussed on that slide) and the "Export Statement" shown in your code example.

The "Exports Array" is part of the NgModule decorator and defines what an Angular module exports. You should never export a service in this array.

The "Export Statement" is an ES 2015 statement that basically makes a class public and accessible to any of the other classes (components) in the application. As you showed in your code example, you have to use the export statement to declare your services so other code can use them.

Hope this clears things up.

**Comment by sipuxd** [comment]
Ok, I see my confusion.  The full tutorial only showed how the @NgModule() directive works with 4 different kinds of arrays... 

imports: [] 
declarations: [] 
providers: [] 
bootstrap: []

It doesn't actually talk about the exports: [] array in any of the lessons, if that's what you're talking about. The Exports Array portion in lesson 13 seemed a bit random and made me feel confused (especially when the services export thing was brought up) being everything else in the lesson seemed like an in depth recap of previous lessons. I may have missed when array exports: [] were talked about though.

Thank you for your help and replies! :)

**Comment by DeborahK** [comment]
The *first* tutorial/demo in the "Angular Modules" section only covered the four arrays that you mentioned. That's because you don't normally ever use the exports array when you have one single Angular module, as we did in that first demo.

The later clip of the "Angular Modules" section entitled "Shared Module" covers the exports array in detail. Have you seen that clip yet? From the narration in that clip:

"What do we want to share? Well, we want to share the Star component, so we add that to the declarations array here. (We'll fix up the import statement path later.) To share the Star component, we need to export it. **Let's add an exports array and export the Star Component.**"

 "So, we don't have to import them in every feature module, we'll also add CommonModule and FormsModule to the **exports array**. If there were other modules we wanted to share, such as Reactive Forms module or Material design, we would add them here as well."

**Comment by sipuxd** [comment]
I spoke too soon.  I'm actually 2 videos away from that lol.  Thank you! :)
