### ISSUE TITLE
ng e2e always failing ; ng test always failing

### ISSUE THREAD

**Issue by writetobegin** [DeborahK/Angular-GettingStarted#67]
ng e2e always failing ; ng test always failing

**Comment by DeborahK** [comment]
The files provided here are for the Angular: Getting Started course on Pluralsight. I did not cover testing in that course until the module where we create a new application. I did not include that sample application here because it was just something we built using the Angular CLI. Is that what you are referring to?

Since I didn't cover testing when working with the sample application here, the tests were not modified to support the code we wrote throughout the course, therefore the tests won't pass. I'm closing this issue.

**Comment by writetobegin** [comment]
Ok , Thanks
