### ISSUE TITLE
Not able to fetch the json data stored locally using the api httpclient in angular 5 installed installed through Cli

### ISSUE THREAD

**Issue by vinay277** [DeborahK/Angular-GettingStarted#89]
If i fetch the data with the same code using server it is working but if i fetch using locally stored data but it doesnt fetch the data.
It is working fine if i use the your apm folder but not working if i install through angular cli

**Comment by DeborahK** [comment]
I don't provide the steps to set this up because it is already set up in the starter files. That's why it works with the starter files and not with the Angular CLI.

I provide these additional steps in this blog post: https://blogs.msmvps.com/deborahk/angular-2-getting-started-problem-solver/ in the section entitled: "I Don’t Want to use the Starter Files!"
